routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('admin')->namespace('Admin')->group(function () {
	Route::get('/', function(){
		return redirect()->route('dashboard.index');
	});
	Route::get('login','AuthController@getLogin')->name('admin.login');
	Route::post('login','AuthController@postLogin')->name('admin.login');
    Route::middleware('admin')->group(function(){
        Route::get('logout','AuthController@getLogout')->name('admin.logout');
        Route::resource('dashboard','DashboardController');
        Route::get('dashboard/delete/{id}','DashboardController@getDelete')->name('delete');
        Route::get('dashobard/download/pdf/{id}','DashboardController@getPdf')->name('download.pdf');
        Route::get('dashobard/download/excel','DashboardController@getExcel')->name('download.excel');
    });
    Route::get('dashobard/tes','DashboardController@getTes');
});

Route::namespace('User')->group(function () {
	Route::get('/', function(){
		return redirect()->route('user.index');
	});
	Route::get('login','AuthController@getLogin')->name('user.login');
	Route::post('login','AuthController@postLogin')->name('user.login');
	Route::middleware('user')->group(function(){
		Route::get('logout','AuthController@getLogout')->name('user.logout');
    	Route::get('/','DataController@index')->name('user.index');
    	Route::get('update','DataController@index2')->name('user.index2');
    	Route::get('update/personal','DataController@getPersonal')->name('user.personal');
    	Route::get('update/pendidikan','DataController@getPendidikan')->name('user.pendidikan');
    	Route::get('update/keluarga','DataController@getKeluarga')->name('user.keluarga');
    	Route::get('update/pekerjaan','DataController@getPekerjaan')->name('user.pekerjaan');
    	Route::get('update/kta','DataController@getKta')->name('user.kta');
    	Route::get('update/beladiri','DataController@getBeladiri')->name('user.beladiri');
    	Route::get('update/upload','DataController@getUpload')->name('user.upload');
    	Route::post('update/personal','DataController@postPersonal')->name('user.personal');
    	Route::post('update/pendidikan','DataController@postPendidikan')->name('user.pendidikan');
    	Route::post('update/keluarga','DataController@postKeluarga')->name('user.keluarga');
    	Route::post('update/pekerjaan','DataController@postPekerjaan')->name('user.pekerjaan');
    	Route::post('update/kta','DataController@postKta')->name('user.kta');
    	Route::post('update/beladiri','DataController@postBeladiri')->name('user.beladiri');
    	Route::post('update/upload','DataController@postUpload')->name('user.upload');
        Route::get('setting','DataController@getSetting')->name('user.setting');
        Route::post('setting','DataController@postSetting')->name('user.setting');
	});
});

resources/views/admin/dashboard.blade.php
@extends('admin.theme.layout')

@section('title', 'Dashboard')

@section('content')
<div class="container">
	<div class="mt-3">
		<a class="btn btn-primary" href="{{ route('dashboard.create') }}">Tambah +</a>
		<a class="btn btn-info" href="{{ route('download.excel') }}">Download Excel</a>
	</div>
	<div class="table-responsive mt-3 mb-2">
		<table class="table table-bordered">
			<thead>
				<tr>
					<td>NPK</td>
					<td>Nama Lengkap</td>
					<td></td>
				</tr>
			</thead>
			<tbody>
			@forelse($users as $k => $v)
				<tr>
					<td>{{ $v->npk }}</td>
					<td>{{ $v->nama_lengkap }}</td>
					<td>
						<a href="{{ route('dashboard.show', $v->users_id) }}" class="btn btn-primary">Detail</a>
						<a href="{{ route('dashboard.edit', $v->users_id) }}" class="btn btn-primary">Edit</a>
						<a href="{{ route('delete', $v->users_id) }}" class="btn btn-primary">Hapus</a>
					</td>
				</tr>
			@empty
				<tr>
					<td colspan="4" align="center">No Data</td>
				</tr>
			@endforelse
			</tbody>
		</table>
	</div>
	{{ $users->links() }}
</div>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.6.0/css/buttons.dataTables.min.css">
@endsection

@section('scripts')
<script type="text/javascript">
</script>
@endsection

resources/views/admin/detail.blade.php
@extends('admin.theme.layout')

@section('title', $data->username)

@section('content')
<div class="container mt-3">
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Dashboard</a></li>
	    <li class="breadcrumb-item">Detail</li>
	    <li class="breadcrumb-item active" aria-current="page">{{ $data->username }}</li>
	  </ol>
	</nav>

	<div class="row mb-3">
		<div class="col-md-12">
			<a href="{{ route('download.pdf', $data->id) }}" target="_blank" class="btn btn-info">Download PDF</a>
		</div>
	</div>
	<div class="row mb-3">
		<div class="col-md-6">
			<div class="card">
				<div class="card-header">Personal</div>
				<div class="card-body">
					<table class="table">
						<tbody>
							@php $personal = array('id','users_id','hapus','created_at','updated_at'); @endphp
							@foreach($data->personal()->first()->getAttributes() as $k => $v)
								@if(!in_array($k, $personal))
							<tr>
								<td>{{ str_replace('_',' ',ucwords($k)) }}</td> <td>{{ $v ? $v : '-'}}</td>
							</tr>
								@endif
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="card">
				<div class="card-header">Keluarga</div>
				<div class="card-body">
					<table class="table">
						<tbody>
							@php $keluarga = array('id','type','users_id','created_at','updated_at'); @endphp
							@if($data->keluarga()->count() > 0)
							@foreach($data->keluarga()->get() as $k => $v)
								<?php if($data->personal()->first()->status == "Belum Kawin" && ($v->type =="pasangan" || $v->type=="anak1" || $v->type=="anak2" || $v->type=="anak3")) continue; ?>
								<?php if(($data->personal()->first()->status == "Janda" || $data->personal()->first()->status == "Duda") && $v->type =="pasangan" ) continue; ?>
							<tr>
								<td colspan="2" style="background-color: #333; color: #fff;">{{ strtoupper($v->type) }}</td>
							</tr>
							<tr>
								<td>Nama</td>
								<td>{{ isset($v->nama) ? $v->nama : '-' }}</td>
							</tr>
							<tr>
								<td>Umur</td>
								<td>{{ isset($v->umur) ? $v->umur : '-' }}</td>
							</tr>
							<tr>
								<td>Pekerjaan</td>
								<td>{{ isset($v->pekerjaan) ? $v->pekerjaan : '-' }}</td>
							</tr>
							<tr>
								<td>Nomor Telepon</td>
								<td>{{ isset($v->no_telp) ? $v->no_telp : '-' }}</td>
							</tr>
							@endforeach
							@else
							@foreach(Schema::getColumnListing('keluarga') as $k => $v)
							@if($v == "type")
							<tr>
								<td colspan="2" style="background-color: #333; color: #fff;">{{ ucfirst($v) }}</td>
							</tr>
							@endif
								@if(!in_array($v, $keluarga))
							<tr>
								<td>{{ str_replace('_',' ',ucwords($v)) }}</td> <td>-</td>
							</tr>
								@endif
							@endforeach
							@endif
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>

	<div class="row mb-3">
		<div class="col-md-6">
			<div class="card">
				<div class="card-header">Pekerjaan</div>
				<div class="card-body">
					<table class="table">
						<tbody>
							@php $pekerjaan = array('id','users_id','created_at','updated_at'); @endphp
							@if($data->pekerjaan()->first())
							@foreach($data->pekerjaan()->first()->getAttributes() as $k => $v)
							<tr>
								@if(!in_array($k, $pekerjaan))
								<td>{{ str_replace('_',' ',ucwords($k)) }}</td> <td>{{ $v ? $v : '-'}}</td>
								@endif
							</tr>
							@endforeach
							@else
							<tr>
								<td colspan="2">Belum Ada Data</td>
							</tr>
							@endif
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="card">
				<div class="card-header">KTA</div>
				<div class="card-body">
					<table class="table">
						<tbody>
							@php $kta = array('id','users_id','created_at','updated_at'); @endphp
							@if($data->kta()->first())
							@foreach($data->kta()->first()->getAttributes() as $k => $v)
								@if(!in_array($k, $kta))
							<tr>
								<td>{{ str_replace('_',' ',ucwords($k)) }}</td> <td>{{ $v ? $v : '-'}}</td>
							</tr>
								@endif
							@endforeach
							@else
							<tr>
								<td colspan="2">Belum Ada Data</td>
							</tr>
							@endif
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>

	<div class="row mb-3">
		<div class="col-md-6">
			<div class="card">
				<div class="card-header">Pendidikan</div>
				<div class="card-body">
					<table class="table">
						<tbody>
							@php $pendidikan = array('pratama','madya','utama'); @endphp
							@if($data->pendidikan()->count() > 0)
							@foreach($data->pendidikan()->get() as $k => $v)
							<tr>
								<td colspan="2">Gada {{ ucfirst($v->type_pendidikan) }}</td>
							</tr>
							<tr>
								<td>Tempat Pendidikan</td>
								<td>{{ isset($v->tempat_pendidikan) ? $v->tempat_pendidikan : '-' }}</td>
							</tr>
							<tr>
								<td>Nomor Ijazah</td>
								<td>{{ isset($v->no_ijazah) ? $v->no_ijazah : '-' }}</td>
							</tr>
							@endforeach
							@else
							<tr>
								<td colspan="2">Belum Ada Data</td>
							</tr>
							@endif
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="card">
				<div class="card-header">Beladiri</div>
				<div class="card-body">
					<table class="table">
						<tbody>
							@if($data->beladiri()->count() > 0)
							@foreach($data->beladiri()->get() as $k => $v)
							<tr>
								<td>Jenis Beladiri</td>
								<td>{{ isset($v->jenis_beladiri) ? $v->jenis_beladiri : '-' }}</td>
							</tr>
							<tr>
								<td>Tingkat</td>
								<td>{{ isset($v->tingkat) ? $v->tingkat : '-' }}</td>
							</tr>
							@endforeach
							@else
							<tr>
								<td colspan="2">Belum Ada Data</td>
							</tr>
							@endif
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<div class="row mb-3">
		<div class="col-md-6">
			<div class="card">
				<div class="card-header">Upload</div>
				<div class="card-body">
					<table class="table">
						<tbody>
							@if($data->upload()->first())
							@php $v = $data->upload()->first(); @endphp
							<tr>
								<td>Upload Photo</td>
								<td>{!! isset($v->upload_photo) ? $data->image('photo',$v->upload_photo) : 'Belum ada' !!}</td>
							</tr>
							<tr>
								<td>Upload KTP</td>
								<td>{!! isset($v->upload_ktp) ? $data->image('ktp',$v->upload_ktp) : 'Belum ada' !!}</td>
							</tr>
							<tr>
								<td>Upload KTA</td>
								<td>{!! isset($v->upload_kta) ? $data->image('kta',$v->upload_kta) : 'Belum ada' !!}</td>
							</tr>
							<tr>
								<td>Upload KK</td>
								<td>{!! isset($v->upload_kk) ? $data->image('kk',$v->upload_kk) : 'Belum ada' !!}</td>
							</tr>
							<tr>
								<td>Upload Npwp</td>
								<td>{!! isset($v->upload_npwp) ? $data->image('npwp',$v->upload_npwp) : 'Belum ada' !!}</td>
							</tr>
							@else
							<tr>
								<td colspan="2">Belum Ada Data</td>
							</tr>
							@endif
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/form.blade.php
@extends('admin.theme.layout')

@section('title')
@if($type=="create") Create Data @else Update data @endif
@endsection

@section('content')
<div class="container mt-3">
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Dashboard</a></li>
	    <li class="breadcrumb-item">Users-Personal</li>
	    <li class="breadcrumb-item active" aria-current="page">{{ucfirst($type)}}</li>
	  </ol>
	</nav>
	@if ($errors->any())
    <div class="alert alert-danger mt-2">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
	@endif
	<div class="card mt-3">
		<div class="card-header">{{ strtoupper($type) }}</div>
		<div class="card-body">
			@if($type=="create")
			<form method="post" action="{{ route('dashboard.store') }}">
			@csrf
			@else
			<form method="post" action="{{ route('dashboard.update', $data->users_id) }}">
			@csrf
			@method('put')
			@endif
				<div class="form-group">
					<label>Npk</label>
					<input type="text" name="npk" value="{{ array_get($data,'npk') }}" class="form-control" @if($type=="update") disabled @endif>
				</div>
				<div class="form-group">
					<label>Nama Lengkap</label>
					<input type="text" name="nama_lengkap" value="{{ array_get($data,'nama_lengkap') }}" class="form-control">
				</div>
				<div class="form-group">
					<label>Password</label>
					<input type="password" name="password" value="" class="form-control">
				</div>
				<button type="submit" class="btn btn-success">{{ $type }}</button>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/admin/login.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Login Admin</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <link href="{{ asset('css/login.css') }}" rel="stylesheet">
  </head>
  <body class="text-center">
    <form class="form-signin" method="post" action="{{ route('admin.login') }}">
      @csrf
      @method('post')
      <img class="mb-4" src="{{ asset('logo.png') }}" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Login terlebih dahulu</h1>
      <label for="inputUsername" class="sr-only">Username</label>
      <input type="text" id="inputUsername" name="username" class="form-control" placeholder="Username" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
      <p class="mt-5 mb-3 text-muted">&copy; {{ date('Y') }}</p>
</form>
</body>
</html>

resources/views/admin/pdf.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Data Detail {{ $data->username }}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>

	<div class="text-center">
		<h4>DATA DETAIL {{ $data->username }} - {{ $data->personal()->first()->nama_lengkap }}</h4>
	</div>

	<table class="table table-bordered mb-3">
		<thead>
			<tr>
				<th colspan="2">Personal</th>
			</tr>
		</thead>
		<tbody>
			@php $personal = array('id','users_id','hapus','created_at','updated_at'); @endphp
			@foreach($data->personal()->first()->getAttributes() as $k => $v)
				@if(!in_array($k, $personal))
			<tr>
				<td>{{ str_replace('_',' ',ucwords($k)) }}</td> <td>{{ $v ? $v : '-'}}</td>
			</tr>
				@endif
			@endforeach
		</tbody>
	</table>

	<table class="table table-bordered mb-3">
		<thead>
			<tr>
				<th colspan="2">Keluarga</th>
			</tr>
		</thead>
		<tbody>
			@php $keluarga = array('id','type','users_id','created_at','updated_at'); @endphp
			@if($data->keluarga()->count() > 0)
			@foreach($data->keluarga()->get() as $k => $v)
				<?php if($data->personal()->first()->status == "Belum Kawin" && ($v->type =="pasangan" || $v->type=="anak1" || $v->type=="anak2" || $v->type=="anak3")) continue; ?>
				<?php if(($data->personal()->first()->status == "Janda" || $data->personal()->first()->status == "Duda") && $v->type =="pasangan" ) continue; ?>
			<tr>
				<td colspan="2" style="background-color: #333; color: #fff;">{{ strtoupper($v->type) }}</td>
			</tr>
			<tr>
				<td>Nama</td>
				<td>{{ isset($v->nama) ? $v->nama : '-' }}</td>
			</tr>
			<tr>
				<td>Umur</td>
				<td>{{ isset($v->umur) ? $v->umur : '-' }}</td>
			</tr>
			<tr>
				<td>Pekerjaan</td>
				<td>{{ isset($v->pekerjaan) ? $v->pekerjaan : '-' }}</td>
			</tr>
			<tr>
				<td>Nomor Telepon</td>
				<td>{{ isset($v->no_telp) ? $v->no_telp : '-' }}</td>
			</tr>
			@endforeach
			@else
			@foreach(Schema::getColumnListing('keluarga') as $k => $v)
			@if($v == "type")
			<tr>
				<td colspan="2" style="background-color: #333; color: #fff;">{{ ucfirst($v) }}</td>
			</tr>
			@endif
				@if(!in_array($v, $keluarga))
			<tr>
				<td>{{ str_replace('_',' ',ucwords($v)) }}</td> <td>-</td>
			</tr>
				@endif
			@endforeach
			@endif
		</tbody>
	</table>

	<table class="table table-bordered mb-3">
		<thead>
			<tr>
				<th colspan="2">Pekerjaan</th>
			</tr>
		</thead>
		<tbody>
			@php $pekerjaan = array('id','users_id','created_at','updated_at'); @endphp
			@if($data->pekerjaan()->first())
			@foreach($data->pekerjaan()->first()->getAttributes() as $k => $v)
				@if(!in_array($k, $pekerjaan))
			<tr>
				<td>{{ str_replace('_',' ',ucwords($k)) }}</td> <td>{{ $v ? $v : '-'}}</td>
			</tr>
				@endif
			@endforeach
			@else
			<tr>
				<td colspan="2">Belum Ada Data</td>
			</tr>
			@endif
		</tbody>
	</table>

	<table class="table table-bordered mb-3">
		<thead>
			<tr>
				<th colspan="2">KTA</th>
			</tr>
		</thead>
		<tbody>
			@php $kta = array('id','users_id','created_at','updated_at'); @endphp
			@if($data->kta()->first())
			@foreach($data->kta()->first()->getAttributes() as $k => $v)
				@if(!in_array($k, $kta))
			<tr>
				<td>{{ str_replace('_',' ',ucwords($k)) }}</td> <td>{{ $v ? $v : '-'}}</td>
			</tr>
				@endif
			@endforeach
			@else
			<tr>
				<td colspan="2">Belum Ada Data</td>
			</tr>
			@endif
		</tbody>
	</table>

	<table class="table table-bordered mb-3">
		<thead>
			<tr>
				<th colspan="2">Pendidikan</th>
			</tr>
		</thead>
		<tbody>
			@php $pendidikan = array('pratama','madya','utama'); @endphp
			@if($data->pendidikan()->count() > 0)
			@foreach($data->pendidikan()->get() as $k => $v)
			<tr>
				<td colspan="2">Gada {{ ucfirst($v->type_pendidikan) }}</td>
			</tr>
			<tr>
				<td>Tempat Pendidikan</td>
				<td>{{ isset($v->tempat_pendidikan) ? $v->tempat_pendidikan : '-' }}</td>
			</tr>
			<tr>
				<td>Nomor Ijazah</td>
				<td>{{ isset($v->no_ijazah) ? $v->no_ijazah : '-' }}</td>
			</tr>
			@endforeach
			@else
			<tr>
				<td colspan="2">Belum Ada Data</td>
			</tr>
			@endif
		</tbody>
	</table>

	<table class="table table-bordered mb-3">
		<thead>
			<tr>
				<th colspan="2">Beladiri</th>
			</tr>
		</thead>
		<tbody>
			@if($data->beladiri()->count() > 0)
			@foreach($data->beladiri()->get() as $k => $v)
			<tr>
				<td>Jenis Beladiri</td>
				<td>{{ isset($v->jenis_beladiri) ? $v->jenis_beladiri : '-' }}</td>
			</tr>
			<tr>
				<td>Tingkat</td>
				<td>{{ isset($v->tingkat) ? $v->tingkat : '-' }}</td>
			</tr>
			@endforeach
			@else
			<tr>
				<td colspan="2">Belum Ada Data</td>
			</tr>
			@endif
		</tbody>
	</table>

	<table class="table table-bordered mb-3">
		<thead>
			<tr>
				<th colspan="2">Upload</th>
			</tr>
		</thead>
		<tbody>
			@if($data->upload()->first())
			@php $v = $data->upload()->first(); @endphp
			<tr>
				<td>Upload Photo</td>
				<td>{!! isset($v->upload_photo) ? $data->image('photo',$v->upload_photo) : 'Belum ada' !!}</td>
			</tr>
			<tr>
				<td>Upload KTP</td>
				<td>{!! isset($v->upload_ktp) ? $data->image('ktp',$v->upload_ktp) : 'Belum ada' !!}</td>
			</tr>
			<tr>
				<td>Upload KTA</td>
				<td>{!! isset($v->upload_kta) ? $data->image('kta',$v->upload_kta) : 'Belum ada' !!}</td>
			</tr>
			<tr>
				<td>Upload KK</td>
				<td>{!! isset($v->upload_kk) ? $data->image('kk',$v->upload_kk) : 'Belum ada' !!}</td>
			</tr>
			<tr>
				<td>Upload Npwp</td>
				<td>{!! isset($v->upload_npwp) ? $data->image('npwp',$v->upload_npwp) : 'Belum ada' !!}</td>
			</tr>
			@else
			<tr>
				<td colspan="2">Belum Ada Data</td>
			</tr>
			@endif
		</tbody>
	</table>
</body>
</html>